language: ruby
cache: bundler
rvm:
  # - 2.3.7
  # - 2.4.4
  # - 2.5.3
  - 2.6.3
env:
  - DB=POSTGRES
  # - DB=MYSQL
addons:
  postgresql: "9.4"
services:
  - postgresql
before_install:
  - bundle install --jobs=3 --retry=3
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - rake