default: &default
  adapter: postgresql
  username: root
  database: beta_feature_test
  min_messages: ERROR

test:
  <<: *default
  password: test
  database: beta_feature_test

development:
  <<: *default
  database: beta_feature_development
